---
AWSTemplateFormatVersion: "2010-09-09"

Description: Configures AWS resources for testing EC2 IOPS

Parameters:
  InstanceType:
    Description: Instance type
    Type: String
  AMI:
    Description: AMI
    Type: String
  KeyName:
    Description: Key name
    Type: AWS::EC2::KeyPair::KeyName
  Zone:
    Description: Availability zone
    Type: AWS::EC2::AvailabilityZone::Name
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AMI
      KeyName: !Ref KeyName
      AvailabilityZone: !Ref Zone
